### PR TITLE
Add integration for pylama

### PR DESCRIPTION
**Pull request by aequitas**

### CODE REVIEW

**Comment by myint** [comment]
Thanks, but I think this would be better as a separate project. Currently, eradicate has no external dependencies, which I prefer.

**Comment by aequitas** [comment]
I understand. But the dependency would already be fulfilled because you would have pylama installed in order to use the integration. Not having the dependency does not break the normal functionality of this module. Another solution might be to use 'extras' in order include pylama as a dependency but only if the package is installed with the pylama 'extra' explicitly like: `pip install eradicate[pylama]`.

**Comment by myint** [comment]
I think I prefer it as a separate project more due to logical dependency rather than what `setup.py` will install as a dependency. This script will become my responsibility as the owner of this package. Thus, I would feel the need to test it, which means writing test cases for it. I think it would be better if someone that actually uses `pylama` maintains such a plugin.

(By the way, I think `entry_points` requires `setuptools`, whereas this `setup.py` is currently using plain `distutils`.)

**Comment by aequitas** [comment]
I did not pay attention to the `setup.py` implementation. I will create the plugin it as a separate repository or ask if the pylama dev want to integrate it in his package.

**Pull request closed without merging**
